.

diff --git a/ark b/ark
--- a/ark
+++ b/ark
@@ -16,19 +16,19 @@ export PATH=$PATH:$LD_LIBRARY_PATH
 
 check() {
     if [ $? -ne 0 ]; then
-        echo "[Error] $1 command failed with exit code $?"
+        echo "[Error] $@ command failed with exit code $?"
         exit 1
     fi
 }
 
 run() {
-    echo -e "\e[96m$1\e[0m"
-    eval $1
-    check $1
+    echo -e "\e[96m$@\e[0m"
+    eval $@
+    check $@
 }
 
 if [[ -z $1 ]]; then
-    OHOS_JSVM_PATH=$(dirname $(which ark_js_vm) 2>/dev/null || echo '')
+    OHOS_JSVM_PATH=$(dirname $(which ark_js_vm) 2>/dev/null || echo -e '\e[31mUnset\e[0m')
     echo "OHOS_ENV: $OHOS_ENV"
     echo "OHOS_PATH: $OHOS_PATH"
     echo "OHOS_JSVM_PATH: $OHOS_JSVM_PATH"
@@ -81,14 +81,28 @@ if [[ $1 == "262" ]]; then
 fi
 
 if [[ $1 == "build" ]]; then
+    args=(
+        "--product-name rk3568"
+        "--build-target ets_frontend_build"
+        "--build-target ark_js_packages"
+        "--build-target ark_js_host_linux_tools_packages"
+    )
+    if [[ $OHOS_DEBUG == "on" ]]; then
+        args+=("--gn-args is_debug=true")
+    fi
+
+    if [[ $@ =~ "-c" ]]; then
+        args+=("--gn-flags=--export-compile-commands")
+    fi
+
+    if [[ $@ =~ "-f" ]]; then
+        args+=("--fast-rebuild")
+    fi
+
     if [[ $2 == "pre" ]]; then
         run "$OHOS_PATH/build/prebuilts_download.sh"
     else
-        if [[ $OHOS_DEBUG == "on" ]]; then
-            run "$OHOS_PATH/build.sh --product-name rk3568 --build-target ets_frontend_build --build-target ark_js_packages --build-target ark_js_host_linux_tools_packages --gn-args is_debug=true  --gn-flags=--export-compile-commands"
-        else
-            run "$OHOS_PATH/build.sh --product-name rk3568 --build-target ets_frontend_build --build-target ark_js_packages --build-target ark_js_host_linux_tools_packages"
-        fi
+        run "$OHOS_PATH/build.sh ${args[@]}"
     fi
     exit 0
 fi
@@ -102,16 +116,20 @@ file_path=$1
 file_name=$(basename "$file_path" | cut -d. -f1)
 
 for arg in "$@"; do
-    if [[ $arg == "abc" || $arg == "--" ]]; then
+    if [[ $arg == "abc" || $arg == "all" ]]; then
+        rm -f $file_name.abc
         run "es2abc $file_path --merge-abc --module --type-extractor --output $file_name.abc"
     fi
 
-    if [[ $arg == "ap" || $arg == "--" ]]; then
+    if [[ $arg == "ap" || $arg == "all" ]]; then
+        rm -f $file_name.ap
         run "ark_js_vm --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --entry-point=$file_name $file_name.abc"
     fi
 
-    if [[ "$arg" == "aot" ]]; then
-        run "ark_aot_compiler --compiler-log=all0123 --log-level=warning --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc"
+    #  --compiler-log=all0123 --log-level=info
+    if [[ "$arg" == "aot" || $arg == "all" ]]; then
+        rm -f $file_name.an $file_name.ai
+        run "ark_aot_compiler --compiler-trace-bc=true --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc"
     fi
 
     # ark aot --log-components=compiler --compiler-log=all0123 --log-level=debug --aot-file=i i.abc
@@ -120,11 +138,11 @@ for arg in "$@"; do
     fi
 
     if [[ "$arg" == "aotlog" ]]; then
-        run "ark_aot_compiler --compiler-log=all0123 --log-level=info --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc > $file_name.log"
+        run "ark_aot_compiler --compiler-log=all0123 --log-level=info --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc > $file_name.log"
     fi
 
     if [[ "$arg" == "aotd" ]]; then
-        run "gdb --args ark_aot_compiler --compiler-log=all0123 --log-level=warning --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc"
+        run "gdb --args ark_aot_compiler --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc"
     fi
 
     if [[ "$arg" == "aotpd" ]]; then
@@ -132,7 +150,19 @@ for arg in "$@"; do
     fi
 
     if [[ "$arg" == "asm" ]]; then
-        run "ark_js_vm --compiler-log=all0123 --log-level=warning --entry-point=$file_name --aot-file=$file_name $file_name.abc"
+        run "ark_js_vm --compiler-log=all0123 --log-level=info --entry-point=$file_name --aot-file=$file_name $file_name.abc"
+    fi
+
+    if [[ "$arg" == "asmp" ]]; then
+        run "ark_js_vm --asm-interpreter=false --entry-point=$file_name --aot-file=$file_name $file_name.abc"
+    fi
+
+    if [[ "$arg" == "asmd" ]]; then
+        run "gdb --args ark_js_vm --entry-point=$file_name --aot-file=$file_name $file_name.abc"
+    fi
+
+    if [[ "$arg" == "asmpd" ]]; then
+        run "gdb --args ark_js_vm --asm-interpreter=false --entry-point=$file_name --aot-file=$file_name $file_name.abc"
     fi
 
     if [[ "$arg" == "dasm" ]]; then
